### ISSUE TITLE
Errors are raised when trying to run the test suite

### ISSUE THREAD

**Issue by jjerphan** [oleksandr-pavlyk/kmeans_dpcpp#3]
When running the test suite using:
```shell
python -m pytest -s test/
```
I get the following even if `iniconfig` is installed
```python-traceback
Traceback (most recent call last):
  File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/pytest/__init__.py", line 6, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/_pytest/assertion/__init__.py", line 9, in <module>
    from _pytest.assertion import rewrite
  File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 34, in <module>
    from _pytest.assertion import util
  File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/_pytest/assertion/util.py", line 20, in <module>
    from _pytest.config import Config
  File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 47, in <module>
    from .findpaths import determine_setup
  File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/_pytest/config/findpaths.py", line 13, in <module>
    import iniconfig
ModuleNotFoundError: No module named 'iniconfig'
```

Moreover when directly using:

```shell
pytest -s test/ 
```

I get the following `AttributeError`:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1037, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/jjerphan/.local/share/miniconda3/envs/intel/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/jjerphan/.local/lib/python3.9/site-packages/pytest_metadata/plugin.py", line 82, in pytest_configure
INTERNALERROR>     "py": py.__version__,
INTERNALERROR> AttributeError: module 'py' has no attribute '__version__'
```

Is there something specific to install or configure?

<details>
<summary>Full environment specification</summary>

```shell
mamba list
```

```
# packages in environment at /home/jjerphan/.local/share/miniconda3/envs/intel:
#
# Name                    Version                   Build  Channel
_ipython_minor_entry_point 8.7.0                h8cf3c4a_0    conda-forge
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0                   pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bandit                    1.7.4                    pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
cfgv                      3.3.1                    pypi_0    pypi
clang-format              15.0.6          default_h2e3cab8_0    conda-forge
clang-format-15           15.0.6          default_h2e3cab8_0    conda-forge
clang-tools               15.0.6          default_h2e3cab8_0    conda-forge
cmake                     3.25.1               h816a3e0_0    conda-forge
contourpy                 1.0.6                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
distlib                   0.3.6                    pypi_0    pypi
distro                    1.8.0                    pypi_0    pypi
dpctl                     0.14.0+23.gd0d3e6f1a           dev_0    <develop>
exceptiongroup            1.0.4                    pypi_0    pypi
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h27087fc_0    conda-forge
filelock                  3.8.2                    pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.29                   pypi_0    pypi
icu                       70.1                 h27087fc_0    conda-forge
identify                  2.5.9                    pypi_0    pypi
ipython                   8.7.0              pyh41d4057_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
kmeans-dpcpp              0.0.1                     dev_0    <develop>
krb5                      1.19.3               h08a2579_0    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libclang                  15.0.6          default_h2e3cab8_0    conda-forge
libclang-cpp15            15.0.6          default_h2e3cab8_0    conda-forge
libclang13                15.0.6          default_h3a83d3e_0    conda-forge
libcurl                   7.86.0               h2283fc2_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm15                 15.0.6               h63197d8_0    conda-forge
libnghttp2                1.47.0               hff17c54_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.44.2               h166bdaf_0    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
matplotlib                3.6.2                    pypi_0    pypi
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
ninja                     1.11.0               h924138e_0    conda-forge
nodeenv                   1.7.0                    pypi_0    pypi
numpy                     1.23.5           py39h3d75532_0    conda-forge
openssl                   3.0.7                h0b41bf4_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.3.0                    pypi_0    pypi
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.4                    pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
pre-commit                2.20.0                   pypi_0    pypi
prompt-toolkit            3.0.36             pyha770c72_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pytest                    7.2.0                    pypi_0    pypi
python                    3.9.15          hba424b6_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.9                      3_cp39    conda-forge
pytz                      2022.6                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h0f457ee_0    conda-forge
rhash                     1.4.3                h166bdaf_0    conda-forge
scikit-build              0.16.3                   pypi_0    pypi
scikit-learn              1.3.dev0                 pypi_0    pypi
scipy                     1.9.3            py39hddc5342_2    conda-forge
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     5.0.0                    pypi_0    pypi
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1                    pypi_0    pypi
traitlets                 5.7.0              pyhd8ed1ab_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
virtualenv                20.17.1                  pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

</details>

**Comment by jjerphan** [comment]
`iniconfig` was not installed in my mamba environment but pip indicating it was for some reasons.
